In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [44]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [45]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(digits.data,digits.target,test_size=0.3)

In [47]:
lr=LogisticRegression()

In [48]:
lr.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [49]:
lr.score(X_test,y_test)

0.9648148148148148

In [50]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.987037037037037

In [51]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.975925925925926

In [52]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [53]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
   print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [54]:
def get_score(model, X_train, X_test, y_train, y_test):
  model.fit(X_train, y_train)
  return model.score(X_test,y_test)

In [55]:
from sklearn.model_selection import StratifiedKFold

In [59]:
folds = StratifiedKFold(n_splits=4)

In [ ]:
score_l=[]
score_svm=[]
score_rf=[]

for train_index,test_index in kf.split(digits.data):
  X_train, X_test, y_train, y_test = digits.data[train_index],digits.data[test_index],\
                                     digits.target[train_index], digits.target[test_index]
score_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
score_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
score_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))                                  

In [61]:
score_l

[0.9148580968280468]